# Generated by Django 3.1.3 on 2020-11-23 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=1200, null=True)),
                ('order_id', models.CharField(blank=True, max_length=1200, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=1200, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=1200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=1200, null=True)),
                ('payment_date', models.DateField(blank=True, default=datetime.datetime(2020, 11, 23, 11, 11, 35, 476078, tzinfo=utc), null=True)),
                ('payment_end_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('home_address', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_status', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('home_address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('manager_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
