# Generated by Django 3.0.2 on 2020-11-17 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201117_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinfo',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='empinfo',
            name='manager',
            field=models.ForeignKey(default=1992, on_delete=django.db.models.deletion.CASCADE, to='staff.ManagerInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empinfo',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='payment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 17, 7, 6, 21, 99614, tzinfo=utc), null=True),
        ),
    ]
