# Generated by Django 3.0.2 on 2020-11-17 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201117_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='payment_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 17, 7, 7, 37, 349975, tzinfo=utc), null=True),
        ),
    ]
